### ISSUE TITLE
Use english names that fits the UI design

### ISSUE THREAD

**Issue by turban** [dhis2/dhis2-gis#129]
![screen shot 2016-06-09 at 10 40 58](https://cloud.githubusercontent.com/assets/548708/15923706/cd56b9d8-2e2e-11e6-9ab3-b1fe98f97231.png)

**Comment by jason-p-pickering** [comment]
@turban , I changed these, mostly because it is not clear how to translate these items. 

Changing them back will solve the immediate problem, but it highlights bigger layout issues because in certain languages, we cannot abbreviate things to the required number of characters. Otherwise, I think you will have to give restrictions as to how many characters are allowed for any given language for the messages, if it is going to be a hard UI requirement.

**Comment by turban** [comment]
I get your point @jason-p-pickering, but we need to change this back for now. The layout issues need to be addressed the next time we change the GIS UI. We plan to do this step by step.

**Comment by jason-p-pickering** [comment]
Well, it will help for English I guess. Will send some screen shots for the
other languages, where this will continue to be an issue.  Maybe we could
have a new issue for "Translation layout issues"?

**Comment by turban** [comment]
Yes, feel free to add a new "Translation layout" issue.
